### ISSUE TITLE
 https://flamingoURL/_pugtpl/debug?tpl=home/home

### ISSUE THREAD

**Issue by jerryniepan** [i-love-flamingo/pugtemplate#2]
this site can not view

**Comment by thebod** [comment]
hi @jerryniepan , thanks for the report! I'll investigate, do you have any error message?

**Comment by jerryniepan** [comment]
do you have supported arr.length in pug for len func of golang?

**Comment by thebod** [comment]
Hi, yes sorry I was on vacation, it is supported: https://github.com/i-love-flamingo/pugtemplate/blob/master/pugjs/types.go#L292

**Comment by dylan-provost** [comment]
This seems to still be an issue

**Comment by bastianccm** [comment]
Having a correct template, this should work.
For example check out the `example` folder, run `npx flamingo-carotene build` then `go run main.go serve` and open http://localhost:3322/_pugtpl/debug?tpl=index

**Comment by dylan-provost** [comment]
So let's say you have a more complex structure and you have something like `src/page/home/home.pug` it should be possible to debug it with a link like that http://localhost:3322/_pugtpl/debug?tpl=home/home right?

**Comment by bastianccm** [comment]
yes
